[[redirects]]
  from = "/api/*"
  to = "http://82.180.147.10:7002/api/"
  status = 200
  force = true

  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/**/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

